name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta]
        features:
          [
            "--features=alloc",
            "--features=alloc,io",
            "--features=alloc,io,sink,std,sync",
            "--features=alloc,io,sink,sync",
            "--features=alloc,io,sync",
            "--features=io",
            "--features=io,sink",
            "--features=io,sink,std,sync",
            "--features=io,sink,sync",
            "--features=io,std",
            "--features=io,std,sync",
            "--features=io,sync",
            "--features=sink",
            "--features=std",
            "--features=sync",
            "",
          ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run cargo test
        run: cargo test --release --no-default-features ${{ matrix.features }}

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta]
        features:
          [
            "--features=alloc",
            "--features=alloc,io",
            "--features=alloc,io,sink,std,sync",
            "--features=alloc,io,sink,sync",
            "--features=alloc,io,sync",
            "--features=io",
            "--features=io,sink",
            "--features=io,sink,std,sync",
            "--features=io,sink,sync",
            "--features=io,std",
            "--features=io,std,sync",
            "--features=io,sync",
            "--features=sink",
            "--features=std",
            "--features=sync",
            "",
          ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy

      - name: Run clippy
        run: cargo clippy --no-default-features ${{ matrix.features }} --all-targets -- -D warnings

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check
